# Generated by Django 6.0.2 on 2026-03-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(default="LMS Platform", max_length=255),
                ),
                (
                    "support_email",
                    models.EmailField(default="support@lms.com", max_length=254),
                ),
                ("enable_registration", models.BooleanField(default=True)),
                ("enable_certificates", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "إعدادات النظام",
            },
        ),
    ]
