# Generated by Django 6.0.2 on 2026-03-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_systemsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="certificate",
            field=models.ImageField(blank=True, null=True, upload_to="certificates/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
