# Generated by Django 6.0.2 on 2026-03-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_profile_certificate_profile_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecontent",
            name="content_type",
            field=models.CharField(
                choices=[("video", "فيديو"), ("file", "ملف")], max_length=20
            ),
        ),
    ]
